name: Build and Publish Docker
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Repository
        uses: luohua13/Publish-Docker-Github-Action@master
        with:
          name: luohua13/hnc-controller
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
